---
- name: This is to display loop concept
  hosts: Linux_nonprod 
  user: ansb
  tasks: 
  - name: How to user with_items
    command: mkdir /tmp/"{{ item }}"
    with_items:
    - test1
    - test2
