---
- name: installing httpd package
  become: true
  hosts: test
  vars:
   webserver: httpd
  tasks:
  - name: "{{webserver}} package installing"
    yum:
     name: "{{webserver}}"
     state: present
    delegate_to: localhost
  - name: "Starting {{webserver}} service"
    service:
     name: "{{webserver}}"
     state: started
    delegate_to: localhost
